// config_presets.h
#ifndef CONFIG_PRESETS_H
#define CONFIG_PRESETS_H

// 預設配置1：最小測試集（用於快速驗證）
#define CONFIG_MINIMAL \
    -DTEST_LEVEL_MINIMAL \
    -DENABLE_PERFORMANCE_TESTS=0 \
    -DENABLE_STATISTICS_TESTS=0 \
    -DENABLE_SYSTEM_FEATURE_TESTS=0 \
    -DENABLE_APPLICATION_TESTS=0 \
    -DENABLE_SECURITY_TESTS=0 \
    -DENABLE_FILESYSTEM_TESTS=0 \
    -DENABLE_NETWORK_TESTS=0

// 預設配置2：標準測試集（平衡覆蓋和大小）
#define CONFIG_STANDARD \
    -DTEST_LEVEL_STANDARD \
    -DENABLE_NETWORK_TESTS=0

// 預設配置3：全面測試集（所有測試）
#define CONFIG_COMPREHENSIVE \
    -DTEST_LEVEL_COMPREHENSIVE

// 預設配置4：調試配置
#define CONFIG_DEBUG \
    -DTEST_LEVEL_COMPREHENSIVE \
    -DRUN_KNOWN_ISSUE_TESTS=1 \
    -DTEST_VERBOSITY=3

#endif // CONFIG_PRESETS_H